defmodule HAL.SelfImprovement.ChangeRequest do
  @moduledoc """
  Durable record of a proposed code change generated by delegated codops.

  A ChangeRequest is generated in a sandboxed git worktree, produces a patch
  (`diff`), and can be applied to the main repo via an approval-gated tool.
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  @statuses ~w(pending generating ready failed applied)

  schema "change_requests" do
    belongs_to :user, Hal.Accounts.User

    field :title, :string
    field :request, :string
    field :status, :string, default: "pending"

    field :base_sha, :string
    field :worktree_path, :string

    field :diff, :string
    field :changed_files, {:array, :string}, default: []

    field :test_command, :string, default: "mix test"
    field :test_exit_code, :integer
    field :test_output, :string

    field :codex_session_id, :string
    field :approval_token, :string

    field :generated_at, :utc_datetime
    field :applied_at, :utc_datetime
    field :error_message, :string

    timestamps(type: :utc_datetime)
  end

  @doc false
  def changeset(change_request, attrs) do
    change_request
    |> cast(attrs, [
      :user_id,
      :title,
      :request,
      :status,
      :base_sha,
      :worktree_path,
      :diff,
      :changed_files,
      :test_command,
      :test_exit_code,
      :test_output,
      :codex_session_id,
      :approval_token,
      :generated_at,
      :applied_at,
      :error_message
    ])
    |> validate_required([:user_id, :title, :request, :status])
    |> validate_inclusion(:status, @statuses)
    |> foreign_key_constraint(:user_id)
  end
end
